name: Prod Branch Merge Workflow

on:
  push:
    branches:
      - prod
    # Only run if the push is a merge commit
    # GitHub Actions does not have a direct 'merge' event, so we check for merge commit in the job

jobs:
  run-on-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print merge commit message
        if: contains(github.event.head_commit.message, 'Merge pull request')
        run: echo 'Commit message: ${{ github.event.head_commit.message }}'
      # Add your build/test/deploy steps here
